---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBzhgYov0NOAVnAUaJJUFbXoSz25Pe9FRu+p9DOohvQAAArsQYd3SaC320zkXnotZVjmZnC+XoRbGOvK2PZyVifVb+syW+UVbQyqk9W8bEPe2h4KML7JEtdhk/eYnAQ8DVyEASv4JVuQAydRTJxa+nlRsWGwVyB2qcqfr5MQScUkkDK9ik88JEv/C77mesn4UgmoYMt8+M+rabndtvvPNO3GU311rpNSs/eM08jCpLUdUkpQnap/+x9398RgY3yGHnC2AQEgMDwpyjWsadm/cNh13y3ggi9pc/dhpjlf7QSQWGeuE8IoxlBL4sVzeqjZq+NeBbfNzS7Mr6xaf87D2pkNQYBBystVmNpa3vRnLNvih0PCDb4E/QPRBbDTUyrri9TeJAgTB1xxeYXO38h3yFaTq9256pya7hBhN2kxAIWcDkx/8m9kchjvqW2kEaXzeGH9osuufRXKBi/BuTQa6yrHFRKtyFa/PS57bpkxQOlbJ4DoyGa5ARVtAREfYaAMuS+4vwo0XpS3AM2YtCjQ/zTIXFY6siNNke1XvW8ouHEzi79lHXmvyKwrjpal2rrju0DzqgoLjdf3Ucm/ePEpPoAEE+GG0kEpzt9okeS6XSsOHlfSizOi6f9cAgc3HhUXV0CVmoBf6ItmP1S/V5XrEJVmk8eJ+sVbZLOIYnDOeIDgql6PXz7d0xJhHh4Gc9cksjO6s6gLJyMDiCth0K0CRGY7A==
  template:
    metadata:
      name: harbor-admin-secret
      namespace: harbor
