apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  labels:
    app.kubernetes.io/name: garage-operator
    app.kubernetes.io/managed-by: kustomize
  name: garage
  namespace: garage-system
spec:
  image: dxflrs/garage:v2.3.0
  replication:
    factor: 1
    consistencyMode: consistent
  storage:
    replicas: 3
    metadata:
      size: 10Gi
    data:
      size: 75Gi
    pvcRetentionPolicy:
      whenDeleted: Delete
      whenScaled: Delete
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  gateway:
    replicas: 2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
  network:
    rpcBindPort: 3901
    service:
      type: ClusterIP
  s3Api:
    bindPort: 3900
    region: garage
  admin:
    bindPort: 3903
    metricsRequireToken: false
    adminTokenSecretRef:
      name: garage-admin
      key: admin-token
  database:
    engine: lmdb