apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: gitlab
  namespace: garage-system
spec:
  clusterRef:
    name: garage
  quotas:
    maxSize: 70Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: gitlab-registry
  namespace: garage-system
spec:
  clusterRef:
    name: garage
  quotas:
    maxSize: 100Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: gitlab-registry-key
  namespace: garage-system
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef:
        name: gitlab-registry
      read: true
      write: true