apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-admin-token
  namespace: garage-system
spec:
  encryptedData:
    admin-token: AgCVzV3gRkJwx7OSTNh5rmV0TsI3uV0wS5esc11uVLVCIbS8paS02Ew1NpJsECoK290UE98vMCPvSfMkB5dRaQ4Dyh0wfvvvBl2C/XJqhFB4LwOa3trzwsuh/D4GICCsGFNYqSCqZXR0Tfom0QIRmrnNxGi0CHNnIW/YNx+HOdjQRpzsZK56gzR4RCD6xhW9saq7fD3esE+0WZSs+BiRoUNV3kTDv2/tKd0DA93F98jBTcupiHyvqjzvaNaNG54Ae6qCGW/+7XZcisnELjVUUQDhQhfnMmUvFXzfBMXw7rLMQfApuD5oEhMwJnP8B4VKTSJD1iNCN1cXZ2pnM/7QFRctzRpRFPdOzmhbNm24VQ+lBlpbJ/Vj7hm6ajsQ/tdq56V1m6O+ON/QpDBnsDoZL3J9+t5Z/lQqkUZpHPnSIPe7lnnSosyHa+m7puC/MmvCvow7EyMcZAxicpJuO52hsEvFW4wqmvIBydgGkzftolmdayy5o/weFWj1q0Rt8cNK8P8s5oxH1VWKJAQn4HfQAmFKlgKFpaEBJR7KxYyrj2COvxEgFA1ubv/i4ZlGVhWdJp19+p8YpdEOezwtHslHKBFQU7mLg5TSjMLcItBuAYnGDHUa6yr5/0Y9K9XO0oMC6q8B1p//8P0u/5kKnYWCOak3/Vtx9+xQYArGbwrQyqOVKCsrm4przQg540B5ujvU79K/12O9QehZko3mSjd0YS21z2KMlI6sgpsBjmPGl2WbWjLBD5AX8bUY7Cnmh9lyA7cs8QFGo7/rISfe1qcYdzpC
  template:
    metadata:
      name: garage-admin-token
      namespace: garage-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rpc-secret
  namespace: garage-system
spec:
  encryptedData:
    rpc-token: AgAYzaVBHNIm5bfRzRkwpgjZZ0EZmOe1TzwFdJbtBK9Js2kHMlCqoWgSkS14+Pf9+/LwvRLrSRNcmiLbeF/e+HN3XEdYjjiqaYLJWbWVCsTIPU2bOq/Bq59pqd+oUxhbwnb20ciy5frhXhCuTGAmi2d394h9PcDXcgoPPVQS1Vh0fxMzfBfWUkWgGk8M9k9A4hJKhWmyCGXHMrZFlKXyH7CsrcCH/eLnJgq1Ll/y21HMK4rqkf3jRf0/DjWyNmIyuX2cfJzaFVUPWYtpGugChS9Ay6z2qBypB5aavyiSDxaV5+DObzx+HLjBxlpQdfR2NFkNRehkPjUwjNiBfSjKc+PW8BcUYqFQgO69mCYu0uSRc2w/oP2pZA5ZqXgsR/TAPpTVy2m0XHtWlFw+iwfpAZOc0Q72DtHjA0W3w+Y5ZEFyNWqbcnTJmi4os2pnnWDycXaKTvHTW8+cWtKR8mhzLwm0mH90pmvdt5rV1y+LVeIYnB/N56+wxEShhqtlOEEDo27JUKXdxL3TTF7hjb/GWiKnZsCdfcjyBp8Ab3uWz69sDZm+LEUCz6bwjxdRQM6wWuzmhd1s2NHf1QHTlKro0uY2ZPLqTnUsExYAYpy93OC+pT/7/GH39n5aMdR5M34Xd3UxQ68+eOCP6McFBfvcxrc1tC+6vwT+GgdjBT9BJ8OReCr4qnY/Wpprk8JoKY6zdikSLY8RrCc2j+eY+SIoGyGeBKX85ec3r7o5HViAIELPc10XNYmn5oz/JA90HUGgOL3UII1Q/HVtLhS+L0rggW/O
  template:
    metadata:
      name: rpc-secret
      namespace: garage-system

