apiVersion: garage.rajsingh.info/v1beta1
kind: GarageCluster
metadata:
  labels:
    app.kubernetes.io/name: garage-operator
    app.kubernetes.io/managed-by: kustomize
  name: garage
  namespace: garage-system
spec:
  image: dxflrs/garage:v2.3.0
  replicas: 3                     # Move replicas out here
  gateway: true                   # Change this to a boolean toggle

  replication:
    factor: 3
    consistencyMode: consistent

  metadataSize: 10Gi
  dataSize: 75Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  network:
    rpcBindPort: 3901
    service:
      type: ClusterIP

  s3Api:
    bindPort: 3900
    region: garage

  admin:
    bindPort: 3903

  database:
    engine: lmdb