apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAYdrGASaoZd4EFVlqPsnQF2fd3oz/KGRhERFFm+7aKoM1q0UvNspD7ji66Sh5NTBMQ0xcjHqzgoau34eFk4uC74s+uuY7tl/KWeMJxVyH5yuiNmXlt/uy3Y7cElmoyDpf3jlumVkOLpQhq80P92sJWZXvKD2AkDHhw5kaEaazTANi5rUX6TOyWuC/LFKpObxLFkUev3KVdxHwb3/kKA9ivzxXhbTqq9ggPVKld0+ZsKBwzL2Xvevxf1izrFdBgJokAO/pogJffDfZOBIG5GnF31LDhCyvRqM8VdJGiejB2yB7rrRlPAS6demgRYIE0UoSJK/bNFWTM4MfPn/4dvVF0uiD30EvYpmGxp6c90Epi2QsnMJID7MJy6mVERTb1+PpOVMWRllHYs0xASDaqPPzsxFvunj8trNEIiVueZ8fT3UMeUcHUa8dpHd0b2qUOzR3YoJoO/kL6Hzq+owWR+JoN+rRbWiRmlfdDGXvaA8Z13pOSbPYwhjUUeDtte5QV7JjxsYgwo4pkXh5u47WaL2SMoD8NOeiYSwhS77YCwnphkjkaZN51BOyDaqwrRK52nD7DXDj34ITVjjsUcq5gGbbNX3CSiJaW3hNF0M9z8OX56C+kUMK5XSqZ9NL4cuLTihsXOOyu65mWeMU2OcKFVmDmo/Tr+Xec+EYCHjDRU2maW9GscDzm+By5/16RmrVSJSV/LysrK9J6SETh2el7XbJtdVJL5dKRDtcpWujLliVpaShTSdDpiqcH
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
