---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    api-token: AgA0uTb7y4dwc2OrlIqnNZhwZTnYA63RSyR4eChzlDZ/YNDVPzaBTUSsjT5VYzWBUbpVlX3FoUmPawPvbRFH+LeVYEO9FkUuyjxslF1xF2kUjBSqSeqwoQGN4V1gsSQ6HXgGoqQQqfmUZvFD/H2a+JSSrzx6ddwAEv2La1Y/MbNKGYuLM27oGsSIV1SoAwDbMEq91nLQ0raIq2fohTGrrzsX944rd64s6omss2EoimGUeGnXxvoNIDxdJINFUex+MRdEHiLOeTGPHR+qIMaJHVQ3d6+RVAAMS96puErGTTp9M70VCcboLUyDaKoHxpM7DDAfgd60gIu3j3zBj5QjhaOyC1SbQWAdE4+LZ1Q/C5wxpvcyHZEaQfgjkBosUk7HYAttwTJ2ZHh99XQKQER6YhZZWNdHE2+wY+mELZcoRYjI4ohKwVxxd72b5Obo8wjCLMIQc61FFJaDHd7JdYaa7Usuob2XwLwK6/QFj8WBAGkxkZycYWuZfE/tYvh2VymwVWzhBfOQkNCra+h2L4UBRqTTFp4DzNsuFbAC67N/PGUR3Z1fw7MMixg9Az728yYbT8UG6AHN+VR5NjJWn1Xy+1RcO8znGFka7Yikh9v4LTjSQpJH22fd5F4z9TvUI0jy56JSZHNAXKVepfKeDWF5ESc5gATnzPDfaJ8c7pfFrS0NlsCETm9UrMBTUGq2cha7EVvyA17b0htdg399a6WIE3CWZQtS7++WO3wPldn4+w6TeUf5LJHkklXX
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
