---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    adminPassword: AgBHAjDTXO24Y2u7j9xLmTgoNukVKZRFs95DQ2TqAlNxdzfE0Q5YZ5yIg/3ihFMA6idoT1iw6ymkcRj+dd7Quoas6WCyj/IxS5HlcDiCr1dV1ktAMiUZKVpTazp4QmiHFW9jgyZgMbfigSM4EkuzAi7RlZqzKEEb0f52o/6U1I0LOrZVQESBLoh2MHtDTTTbXOp4VDrJepnBBD5urmzx1uym8VAnZWtxfFU3k8MeXFLgEyET0zawaU/MQcHBMD0kKoq9SNEQRLUUyO33J0OXb/k0y4CKLaBWO5EVHxIh8E2IH9qm4/n611vk8v5wK1+0tTcRJ4Cc2C530WGeV89g7EwIcMedsD7kZZUW7H9rNBDG+uqi1PHsEZqQ58X1/giMylYXZsi0TSmSBlG3Ex9/01yJmhrvwOx+qLMDWfl9Uthb9rLmoFyCtvds2kGvESLvQugQMqHmxdWy1ATMuLSFXknZL7dkcCpCgy5ggd2wVNaDNb58dYO+4SUYJ6jlrYCELnzmWFjW/td9e7kNDNzYHEdPUzXPwpJkaNp1IHgOzeofm/l2+Gy5oFo1jAIoPlVxMQ+TnreyBEMs94p+o9J9+ACl11+Ho6U6DzePoEDdugUoT31XZZSeNd9Wg8A199/vTYHSsPcTdj+Ps/upf+XdSdfWSqWb/N+ZAFwe/WiQu8lFTLKRKse0Q2fwPndRoBPBu/HIJI+bbAydk3/K
    adminUser: AgBquF5NP5afcfhkEW1KMXfVSWV2gvbrGedWp5Apmtr+rBgrA9JWZhFQjHTdQa/mhzgSZPEFRjZZJ4IFLS78ULqMlb9z0yjtUxm4r4Ox2+oe/fIaTwwbUhmilknMEUEuI8/v8Mhd4p6OQct10npHsBtW5l2IcdiKxZMMy5/oJHiKJ/x4AiZaK0taBcNBji+qbl06hcAFt7zUMsv9LlRW3eYkchZKEOkkXi7vyhZ6lpTBfrcBuvTU2GwK70Vdb+lCfaHQw7G9HHOdKpB80ti8Tz7S5W0RwcPGv3ZIlig4wl3oogUnE99Ng37NJ7fMckQX0lS4Jp4qwog1n6kGVcvq1T0uZ0ZDNMECpHwKbgwWmhsv/4TzhnyZS5e1YuC+WzhRQ9rAHeKjTYafEiZoyfZQGF42mUm/kMr2NvmhoFRKwyU3ya0UH1nLYtsEq9pvLIO7N3vfg0CZg1EOfU0/9fXy+90ImjHTcsz3dDOJg0WekDh7M0TEfZvi5RIhlrVZnEsi7z5vbVdSkvzhkezu7IgEN91LoDcPbKaNONhPsA/h9h52j6zsMIudpq5we3kWw3nqu7azP09wmZrlMKeYgO/HEWogVRbkWHfwN3NAR7XElq3MTHB2nZVSZZ9w6uZ7v842oYnvtbTyE11dfXE9m/a2qQXW8M6bJZ3I/h33TDu2E/+5ghsLB8rIEfQNhZNO6VeRAJrrBRJl5g==
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring
