---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgAdH2nUPS1wqNNDCzb2VakFEr6LyqtutO1Y2UvpHCxQBuquCFopZTOzjs6pVaeFTXu86esFBdx9JyIOI7paIE2nqgKm0vAxwJlKNIkh5Nl0AHPKCEPIaRVTxbsmHisnAMXCrx+GG76r1/SW3/tLQqx+39bTYGes3aaiLpGv+GEIlD/K7/mr7bsfhIKXCZ+52NgVE24xxzvQFzuvc+waDDlK7YihJOG1mu1UBmATr7lEsdZRj/IHt2JovLya2ZXUT+Cu1WFHwO0FKuyRm01jQ9A/K1yhdtEQi/0IViLC3jHemeWqYlO/xJtZIDiEt5IrbnjMl0RizTk8ZHKbpTeoD9ubILmfNjcexB1BpMfRHGpRS7fdTHBLqeS6wcPfZsqPLM61IQ9FILvn39tJMCr9OF85YEsSau3oIQ1P/CSstxMcu7pF2TllpQZztpRToa+EwUwFILG71egN2bwfmUn0ejeJmlEtgJzTg52gwY2d3qzSFXerPgwzT073kcrz0znSFxt+GzZab4H2TLnTitIGcd519/kS4b+nV3ojn4NJuSpW9pWDcbAG+BWLQKWgUkMgtHtaygEUStthAQEdJ12ojYJBKyG/ii6q2+lK66rmFQXiiHtQf12yeVFBWJRp87+uqK7/BMz5TQcuRnpKOSJf+xstOraDjdHTNoyBBzpHbH4lakwb6IYAZZgz3Gb2M0aSEL2U1wi2sG35vU0io/Lyp7VrJXyykl8uSL4cQ34zzkGzWYgpbfzNWLU6GN2X8prIxgI445o6GLBdqYER2NuGL5BUBp1cYv48VgNwzXecxlmWJwkHAcgmyD2SQGQtutlBgRcs6HHVq2jEp8oOl2pMRR4j4rSR3YCJT1FD
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
