apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebook-nfs
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.18
    path: "/mnt/user/ebooks/"
  mountOptions:
    - nfsvers=4
    - hard
    - intr
    - timeo=600       # wait 60 seconds before retrying
    - retrans=5       # retry 5 times before giving up
    - rsize=131072    # read buffer size
    - wsize=131072    # write buffer size
    - noatime         # don't update access times, reduces NFS chatter
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebook-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6Ti
  volumeName: ebook-nfs