---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-creds
  namespace: media
spec:
  encryptedData:
    RADARR_API_KEY: AgAbpV2INfTWOledRTtDLvT0YsBfZuQ6ieBZJHzMXqnImvXIEW1ibrxOqZBAJnsMZZow8xxncnwJCNhO3WYkJmgDaCp8ROMdWcQ7691eJ+a22jop4D537oOE5SRVu3R4bNeufJ9sNAHWE4G5sscAJQKa4DjmTJ2vxP0ikyYdCV3UdLxmnuG7i+ykTDfLF3RNysNtH/QwXbQjVJV0FWABWWdl1Rx3XtBrWXQvAWHKcV1dHsPGVbeL8A10Qb9MkFJZdAkcHUitHaZVel1tnytib8rnsQVvnneyYQtKC++81QAS2NPmclJa3RbKwyopAJRshNjoXmRdO7XPN1rpzXsAn3w7stfKh+hAtVNzE+D8ES8R/6bH5SDxsku6Iyp8HuTwa+1zR+SzmGkR76ixzufXmN7O6AL9zA1vWQRfllMg89uknabYkGKSISpgwuTFfPqL5rH217L3vs3YBawEGZMk6x989eH8GZNhZVWZ9myerxwAZXhl0L23+IBbfix1gGnHUWlv9DaPY4E1Mf0nP0MENHgSgGP3LtoW4Na8Pub+zvcm6SrkJvyPC9rkiK5+yVjrJ0wn1aKY3BDzrB8wd6vTsDzW0gtpjtTzWrH/TeXlc4t0hvHPmxj2/pj2mi22mFYmo2hE/zXyu6RImPXXSESKF8E6FsfM/7/OHhFaypDa1BMwDY7quFmd5TL6oiOP0zOwkbTKGBfiEvhWCJl+F7G0vkdS0tJUDRmUAWYqxWcHwGz1uA==
    SONARR_API_KEY: AgB4/yr6E6pRMTIM+ItUQw7DGPvYZOn0zEOVvK+LzwCpgILGUvScE5IEWCYOMUv1t/6F1B2RkyVOChdToYF7042DofsL6f8fq/D9Lb7sO53mA1n0prxFVMiLR37JsVn6XB5Xo/jqNt0PHg24361/qUijJCDmeuH6THXp6EBf1/faTXYaAxUs6Zp9wahf2sGN41syzeTNahDkod0jQuYtFF/b45W7d/rgabmT9H141F9WE65+sztTsh/RD92cnUpJs40yQt7NY1R7u8ux8SZ8vBLQSDZRE8XoMrfe9n/0+qzmTY95MSxJcPR2F4jttMNx4Oc5E2fwkR0JTLEtO2yaQCbrURONtNVF2ZsjSLyUYdeEIGa47V4x97D4eWkHvCcRRnvgBQyBYUuQLGobBp/eTky64NB7B6z8IbFelhPo+uRspsfUJYgQMUuNYuC1zzciuBUTtjZTOSKG+SL+YFuX6FkeGW53MkW3LgQomX944mwxr6/KuRCFeQPoh6TyHe6yyNSvgozMGruP0UlkNmoYelniHbc5voKjB0q9pSJ2bFFvu/xSIpa9qLyaM/qDxf05xp9BxF3C48LRUWBmoy/iZ2hgbGo8lHLKEh22RpTq1v1YWYebj+1uq91BK6MLIPwGyXleeBadtfuZxD+U+aMmRpC0n3ZBuPZf637P4KAp4oYN3Pz3DZclQjcSM7Dmk99TrblgMuybkg+GkqrEC0VKwayGfPGQZQ7r5dOYWA5r5h2Fwg==
  template:
    metadata:
      name: arr-creds
      namespace: media
