---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: idm-client-shelfmark
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    CLIENT_ID: AgAMoXbK1h0Tyk1zJwScUiPU95diNjkYBGbZJeL/BHTFyoT4AeEDIFxoIAXQL0rgZ38LPb7kHXCEM4TpKhxbhh777bvdKmaKCmaxDPTHUrLFLTcVoNghk6Sw1efihq6Iupya7hWeOv6VsZYWNBx7nKjtVyiUmk5RY3wJzCfSB+Z2VN8cr0c2Rd5Fvfx4VMRGTHHr2wS+X0OAPoo1YcVn5gSaZtAp1Cmxu731EF6C8KHOWLfj1JLe1Z4AwZPvoy6ORAEue12CY+yVigQvHF92FVdpockJMecQg9Ye1uFwNDlvXpw01sLPiBJcAuJ+qqSjqd7flwBJf4YKvgevf6Arg3NnQd3g/Y8YJf97hTkUU38nlxLWAIEZquqAlVT/brYnaKGG3MZdVvX64W6uDNmXpD7W3XnGNfAj7JQQ5rUIbCZEGP+YqHA5vRRZXAyj7d7T59AhaznZ1kd+78EUFPWFbqdmb1I6e0yYkAmAUCmAlDiTJb03hBOmLZcwvVmrr4z6/ws2j9Z2nHfn07UNuKmQhzZR+S7lL6sN4rGpUtIQp0FZHfDdC7maoPiI8tf9N+X+rqj/bX7HQkghvtmoDXZR4B+8zjuVYWN9zLnwX4gqBv6fZcWZ4V+5/UQDOU159sm4Ul7dNPJJPSfxvS+vJaFTsj7Dq3ykErecuRIwsSO2s1yGKN+gDo1MGc4O9Bzi7e3WaNDPLre2BulEyE5VlbedbZ1Z7LhhKfQGB3qIRW5GEurmqWPhVDcaF+3f
    CLIENT_SECRET: AgCNIWqnON6qVoH4s11FxRaJWLVStseUi/qIr2Womw42Qdf5A/t1CtNgzpwd8Vitj7PlKqEATz2ApX24mLsAcW7Rri+e8EVDNTXT8j1ymhGfWL8evcwSeD20XTC1Qfr9sY6FgxYdlWm2gHpbFv8F22f1BzBIHhS7Pgy9Ch7qI73Y53s7uvNC8BOPoztfDj8ZmX6QwZfb+peUSgbcxSuZvKXSnqYKPSAW/5/sEZTplOmNESuDktyLhJBpK3NENMcpjWmO5+BX5th1CABwmJjdmRPc4SjZb90r2YjLaYmkrelE302Esv56d1rnmeltOoO9Uccj1M3D7ZrSejvst0BE3xZWwYktgawPU+q0PHS6E83wPd7K68rpOU980K5WAhzxQzlVq9H6sY6cdoC5Z/3riiwvEr+euJIKcZVdBzUeAC5bNPEDSPJfzlBKI8zsYQgfX5wXuQbQkqK/3gfpMd2jHUbPZv25IeWj0sGkYGizggFNPh+wm2Eso7s+vB15AuJjetpFKrsikhFppE5WIBQvB6U8Npuw6/N8UTb8N5qo8LyaUDIqz9q4Kka/KjdKI0ZXiAwRjYFdBGnzpd228NVHt3gTePw0/cQmPar7/SsgJ/WOIIeMGY+wVOkcZHVtdnW6whMbKNaVb/qyIESujWfeGt+B7fymuArGiVlz7NUXpPaFgiUPGTz5SKPFpmeISPaxHOXHZvpeWekFIRW3SI9Jexyl63V66a3EOitHj978comT01bRapl3WOdw
  template:
    metadata:
      name: idm-client-shelfmark
      namespace: media
