apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data
  namespace: idm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi