---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: idm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    postgres_password: AgBNzEuTBiz963ViEY8G0kbDCt2DILhWp72DQWd7ibWgCJNttedHYX6iTqHFy/B+8rfixpF5/ZZwG/y7OhBrndI8EAN/xsAMsRVWkkTvt5O1y4NNDtK84GgVbpyXDDlG46fCgejQTrpv8f+fBrBkN0BEsnbFSEOKWnaBcS2ILCaN4XINP0kYh+UpV+ikOagKnGqOXJ8Y2mRkV87614/mheGrkWDf7SQGIkJy/JsO5h90Z7hsR/UXuVraZ27Wi6VWwE0dFo65ge5imXJf5uDJydl7Itbf26fcMx94PkXM8QFcaD1Bu6rgMPueCMKH0S9w+Y0D1Df3Bbz9sn9HTt6QhBlc2vAC2c6jQ/BrCL04QsQCwDNjLkp7ptl0FmP6JcL2J8Ng0+AWMAWkGl3VDh6B5gaXlI/17djJDwhGLm5Yce+dQ3JilTI53KZsL+Hjj28mRl1gGRFeG4RzfeNccEYa6FLdjwz3PTiNY5L/exHVo7z3pdKJGsi50qQFGTp/FNGfleEilRFDmqqjXCtwFH2KbCD+D5hMoPjdJVnbkGRPmmeTrW9MN3vaGTffYGW7g3PvLZBXnuTUqAYGsoE4iflEIjOyf2Hy/MSl++6+e7wBMaGSyLr8bTcAzKxJczBpR12I4G4r+7LNRCcD7CYO/94ekmgi7JfVjvvb9HgjgLAQtmRs/Swi5LvlgunoHZOBbD3qd5CGUGcr04wo0fjWf6aOFE6lCGn4+i8GFTX+Ykkk3H6YrVf/6K/9WL/UwQ==
    secret_key: AgBgPVAAhI6TL2SPMyTlFlMcefg+Zq09raaDpIuWwpRLagj38CmKwRWMZrXnMSKAFS/OBn/5La48dkbKgj++/1BcwqGkcKgfONTBi4Mpuv5X3xwH8mpJyA1VdkqyKCssuncxBW6Ipjp6rN1A3uMq+zZ/qZWsHeXVHDnSZWl8xOhVM75dEGm3l3DoctiU2MoGeRwU13WzrbRaY6ELRT7hnPhke8XwVL09vIKrkBqiKcW2qlnr1oi3yLO6vAOWOeca6sSGUm+HCuVAD3q0+TbFpoVOz6+BCl+vL4zTaNPKDNs9gFyAKYyFKvhbTzjo6U1WILoPky/s5CERv/9mDt0U6flhVO4nNkB0NEpLK3VeQzVI1rsBdb9SNijxA2bOoET0v3O4Jdk9odsvFbrQivKdQKM3VHGZ25/BAAVTIN+4psd1X7+7YgP7a8teol5r95YEvY65XWmQjJpavVtT3c8K8PTsqghlcn1jVw+9DdXyXfXpqJWsxXK2xa+MsTth22xPrvZpspswdpdbnBOOmzNmYEro6MhSJn9lo+scGCHw2CxR1zF0k2KIXO/6JHuv5BTmU82m8ahnH4KIg9/qBCYRZfo1Q9Gypz+vQxN8lQiGSTS3wPJ+wg3yDCJLi6YpHYGPVrX9rZV4ePNpxUwMLMxCCD7sh6MjApb+U9h5kEhOJ8NsRZDawpckCh1g1+emXhpxGVtqXWW3+vj/bUYgGO88D0iPk279UwT3dKp4HagCU5kMAnad1QjIpdmGW3LFWFE=
  template:
    metadata:
      name: authentik-secrets
      namespace: idm
