persistence:
  defaultClassReplicaCount: 2
  storageMinimalAvailablePercentage: 15
global:
  priorityClassName: system-node-critical
longhornManager:
  priorityClassName: "system-node-critical"
longhornDriver:
  priorityClassName: "system-node-critical"
longhornUI:
  priorityClassName: "longhorn-critical"
