---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: idm-client-calibre-web-automated
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    CLIENT_ID: AgAi8xG7JGKfEAeRW7d1DrLL/BXMkpJZUIHq1scWng976GvOn/kN6S4BYETMbH+kKp2SEiIUCRUmDMtiLPDzqKllKQkMMeGAbOiMFdNlvhWFEJ+GCTBAGHszxhRBEhHworrrhLWOxO6290bomLh6uazf+3IUKPWLIYI8QrCVHWi5V1GkcfgMCl+j04NYw2YsByaIUnJ1q+9A2m2Tw+VzB8mj6ZJyJ+Ut4rMCrZd/xX0uGAOQ3067tBTFRU4Qxop2BsBEMMShCcZK4YM1r3KoBIpRqhfETx9rLT3DgR22sqz3YCutyczbRHKGAiW6PPrygHOWtrJrvjOFxphMxB8V8fpTOTrBJSmcplKoin+ExP/ufmuViDBPqHFLSE6FkpZ9RB81n7xPJUM8RXsdIja7BUBOOREiFJSL7XG+txzLlVmkRGd2s3D0s9rKYZVOBC3+Llk13SD71hjqSMz05zuXxl3pH5mZWk+XKiYX27n/4su1MyrY8KUGXfD0xG/A22B+2wbzDYMxArglVm2LsOEZwDb29RWy8fah14UDxRqO84a3dIXG6/oGnNNXhfqP0HDMIAEzZ8qBAcbmrHaYKGFT2UKasecmFWNbo2uq6bYKQyOKzlQszcxrpzaEuOraBsx/pHYXD0XZiKd4mpqmSIyh69MtQiNU5P6VqFmnDJa8xg9ur62x3f2yZozKxvru6194zUaFBTGY46vLfYhjnXoPLc77/w+MyFeku90jpCPjMq/k/YZpb5P/lEi3
    CLIENT_SECRET: AgCEvV/sOllYfFgzDl0NTUDGo0g+OBx5X9DUAgkprA3XPhJ2Ydy4tsgUnoSUWXUEephCF/cXlGWLzZ8pXFeBNxzFZe4j/PloEaJBxkLiOrSuX/rMsOwE2NY5NFy6YWYWnXwD1lAbkr9l5j8WUrY1wXp3lVM4M6ForTTHuvbbp+8d94kaOioDacUadhwPmyb0MS5Un4kIn0Ma2jW70Q4SW/7erQ0x5ds2WwxRWd0DDZcn7sDUaFhS1l7fvqoh/K+LAx51mIpFrvHXwk5PEaOFR9RtCLeQt8B9oKG3pzRXEid29+Nr3E5ze13VwTLcdliHq7pCxHvlDzYt3MisAJQZMgHHfx17CDNeAojFiAeXaLOMju9YYDQ8z7ap5aVwvxnmKfMEAbV3TMxWQ1RSsRAMlrEgXo82HGCIl18g0UNgjEiZ1OI1uqggPRGUaW6R11jLB/e5KGlDb76NRLOtZGUUL6pybceDMOPX4O9ieVdggNVUVHDi+KiWCp9eYzWw1rNWDQ7eWFNTaSrTlzyUxaObtkpJcL1uTr1bT32JVPNwQVN6fKCq1nUNFgp2i8LqKYRRdDnhrQtVM3B5KU2kVRkhL1xeuvJL9vCkC79yDtzNI7knzzlckxKHd734tK9ZpRUBTpYE6cstkdUGDcRa1iFv1kJQ+P7O6n8cY/jHdglE5sx0/BYKpx2G9WgyLPhdAstxm80H6OPnyG6zUOiXYRaOxI3DHCRFpju9KfC6TJsDb0PX+DdIvg94aE6p/t9uNQCtuTGE6sBfo3GKEaKNnrZtdRCMWFfM47CG/soBtOAkI/WIX0M9WKqVP5f9T19xEiBC6gifuRmmnQj7MQbZZ/Ait2wr26onTVdg2/AorIGT+7Hdig==
  template:
    metadata:
      name: idm-client-calibre-web-automated
      namespace: media
