---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt
  namespace: peek
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    JWT-SECRET: AgBr7rKoDVcSGiKJu5tzrHSi+7M9WwRQLK12HMcMkXzZdxoGeFK1O2bzFOwr1sX9vmgvI/f5NfBbxL+cHNH7zA0jDLN5YZdYeYCE6U1dajU1hikkEqYziMnVYaZjR1NsY+peA7+/NHdDC3HMfUj6zgDHqEVvtZTIGOgbsQHuvafbUOUtaonCbuUhPmklgCV2KATIkroYsV3kPXwZJrnb5E7xZomhkDAKZ6dfXkJQbEHWNar9d6GWJHydr3pdMsjSN+nZpR+A3Q2bcnE32dXAhFePinl9OWF1iV344E6IYgXmZGgsjZwGhOb3evMq1pU0Lii1SnstE66sJcgNUquGf+cfOwfs7fUwDYG994joWCNzHCqgAS8ZdVnYN4UN7cD1DbD+Ebv92L1ZNnJIsXQsgq6caZehMPq9B62GnKwvxN90mdCzywOsU1lsE3UYa91FFfjfG1l3T/WL7m+/sqaIvqsY9oBGyBI5NMVOhe1bTQRu/hdO7GcDqXTI50BGGmMVkTxsFB2q/z3rdCDBmkFpXwHwWji+gd24yHW4eeEmq3mANZCap0xOxr2R6jSS/8D+85tVX0SPrhxVwvrCK1bagqzaK+NC/P2zl7qTl6jzORt6tmChWCPPuJ15dmX97Mwq+yImkAMsBMdMKWfBjAZwkRjBYA2R/NiKawtEe+P7MMhwkd7Y3sg/QzmO4mcDYRRBuTP2qgKwnJaVlomQL7bAXzb5u0uYLGenet5kzGa/IWit8nG+D2Tv6R16fMtwmw==
  template:
    metadata:
      name: jwt
      namespace: peek
