apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt
  namespace: peek
spec:
  encryptedData:
    JWT-SECRET: AgA8RMyCWU/1ZNoku2WA25aJMXmOepvwCEDSaMsS17UDXih/CBNLhfMtq0Q4aYYgcFpNuilF1kW8pZRaf1Fi+S/eRrY8lIHCh1kNjjJLIpH70zW7bfzsQ0eGWoYxl3p7xGSofcTGxZhvjDgywiuNvDAzcOb1DeLifX0t/UTEib39Dbag4pw3bukElafZJuylgcraleciOReStZ4U4907y3vUGSGFWgNuCOr1lCUtlFv8cTIX64TGFE4uydbxAjb4khLn7kwvm9YIz6cGglrBb6mkefM2fV8xbKijKjAZ3w11rl0KKoGW+yKCiKhhRTyEt+5XcLMbvAaWwmZ6djymPJw9Z93LRTnyw65ZQoSCp9cnOHNmnQ350H6IuK4xKdLyRGtyM4ST2A9cZCVonimL6RJU3u8dIA0jjmH6tLV6F7lSuosU1BUeLYe4e4V9GQDWhitTPoRvJg4pJCxHyw72snW4c+5pspLrc7/DicyWB1/euI3xp9gHVGqowY6cBWVxo0ngAzxxPabcYpJCYqyUpNAPVUpivzbirNbdh659jd0CDfxY/quwzg/37Y8KnVOnSVsC0sDy4AU6/G2PegPmQLnckFKNKZYcTpsscqmmt5u9z5yRlTT25oKMXI9uWU+kqny31/YGmVePcQ2xRcx8nYP6eqRCuFADKr8T2tobMN0cnyRDewu1+e2f7L/oktlNU27i0+74NnAe3KrY1j5/QhHAt7cPtSTuiseFV1lj2TG4WshCiPCDWKdpgn61Rg==
  template:
    metadata:
      name: jwt
      namespace: peek