apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-data
  namespace: manyfold
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-storage
  namespace: manyfold
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
