apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: key-base
  namespace: manyfold
spec:
  encryptedData:
    SECRET_KEY_BASE: AgBeIKapVtQ0DGglaTCAYu/VE/55UcQxQb/nU29ZHd8HrBo6aAkbWrTPWPIlxM7NzxxRVrwyBUYaYzUp1wn2MHT/DlmLTH3KGQMqcy1JO3FU1Vja3oTajlwqkSTQTD4Jz0olvZ5MiSNLm0emFecxNuCYy/0OH7FH1nqr9V+m7+9Zj0iMW8bNsG/KpOw00xVCRd5901Uih4TPcBnlRRJt8vwdFhRv+bvOP0iUCb09TAKwGUOnKTsPF21KVkvdSpLU6sIXWnHSjkLX3Ii9j1ZXDQLmabZ61iSTYtQYuZWtXq6nTreulr7ghVGcrizbVgaTUKUrzVE3h8rt43PJszTPeU8f604vDayqKd9WUGI5LomfFwe5jwsLWlRMPSVHN1arXIwhg+oJd921E8192BYPgMEg/k9oNBDr2oloQk2HEyyAyYOEz3akuU3zsAIyaWgTa54fCzAU1s8C4sx4UH0olc5mu+2MO13xmHf6I/RoLAlAS8fW+vJF+Py8bd4PYjKj3k+TPdxBKD8n3kHDaf1tABWkU87Kag/75nCJTBeTDy2Gkxi7bpG1CGPZa0NKjPsK6dmnhLcxCFlravUABPMceVx763rC+LWRwQR6b4xZwOkdOHOX2utFXZYDF63HEV2e2bkCuvHc743Ed5iJwxezNOHjxSM5x2fA9fLE7jUmMDnO1JevZBDQo7bVMTft/p6kUV79v58P33wzgQDsUhGaWxM5XhrqeO0GocQcsmASUHApJ7jg2Zm72b7iW22noQ==
  template:
    metadata:
      name: key-base
      namespace: manyfold