---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: key-base
  namespace: manyfold
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    SECRET_KEY_BASE: AgCen8XzaioMnIhYzOoB3DKRuc1PWg6QNc4ykkNV+5A0K4TNPYvzcdwMZtbXr/ZYeb65PMGa17+Com0kkUR0IoZUQU2kGUFms4YAOzNyxPIxJa3kbDZ3LJCyHzx5Mgh2fv6e27Lc3uwknOcDOR2FzWGmWYY47BnQAj8W7OWGTX4YyUzXziN31Eh+X6Ojt9ESbM/sKsyxaEKm6rLPKxC1dLML1hkljWqTTx1arFQtZC8QzNMgjcZljZCCnVMFPx48ges6JOB3DFuF6Sd2bsSa3fRYYM/ScvhSk8p/cMkmh6zbYxqAIF5rRxXKlDz/hhDqIlujNyig51VatOHmSe80zftLwrBtnGPOvFT1tkOC6FsaPCGQee0FxlpXKRGImpnXcqrilcfSwK+Udj6x5Wh8aZ6JaO/iuSfaaGJ8qYvwUBfr9iAwhl9cnTbrMuoyYRic9FIxQlnlfzWBqOu0mPVNzHOubThlDFh2AX6J/w5/XOsdFiv17YQhKuqUlG0SHcmQEtO3wBdcqxytTagr0tHp3kKPPiT1oP/gndBvor59ZoT3tCLPK07IEjWRDMwgxVCWC7bNXOymHg18zjAcX+LipAN6WuQh/3PG0GbbKmkZNSS0wGT/8qdbtM2JmrMQ1AWP+LGftTRuHp26w8xfeG4M21OoEFEp3D0chp5n3yncIRhIMT7OAExNQ2IB7Qf6b7my82SP+HJG0P41N5TcUlR9eVos5Wghh72sqlBMj/g1YUv2Az5RPogbl04CVjELsw==
  template:
    metadata:
      name: key-base
      namespace: manyfold
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: manyfold
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA6ccEhavoRbG+Bnf2sLhYXhWueLOYbRiVczLdmE1z+uvmnDOhu8hnFXfK7V2+lnqW/FPBllPs5MVFhG1hKzFZvUwuhqF0qtvd6ZgyZfmJB5d00++T+PXgnu1gLub/g0Y+V82b129i6kGfIfSLifP1gvN+ZjdVPOeFzcVkWCHtYpVx7UZFRdfDDucuhhN2M9gwoC4PU15PrKP7hmOl/QgO2DOUeAMKa5AadKQfj0sY8MZNIdwBswxIh99G8dJcElDeplUyX1ej3GTaSw9sFrTRK/ITSimoebWZ2O2/1ll++HvXQr7nmR6+tr8l/QPdr0rZnrSFDwfoQX15K7q63EhRFZqI8/JsUuDw/o8AV1g2pLRnmaXhFt2ztPSNU9EoDcP1DcyQqLbGX4d2BArMyb9570P4xgCNk35f2E1DDBIdMFoFTWNOq2qwtuh9DVEEoUqWNSr9do76tUuVtnpw4Qiwj2V21xBX/DeCnzs83/cHefTqwpwXeD3JEDMhwCBFqvG4vE/xnxNKP0QM0jvxCbHw7hwZLjNiJfesRmR9sDsBavXJtz3kgSQhTwZLXQdvnVbnndjuIwUHC/9tqvrZ8Tw8VAHjx7VbVm8KoTwu13DWyuHuUETHNJe2BKR5thSZzVcf5V2vwBZrrYBAJ9R+7dnTmOqRmzr+OtOm33ad9LLL3NvVXcYFK1znnO6JNgdrX4KWkp6115u9EcrJWkwlrHBX9DnSZ15oFCM1SsjEwBTvTuxO3sorrujw3Y5Bkyw==
    POSTGRES_USER: AgAffk+LGlgu1fpUwE+0OuPmVfb7mXNMKdE4jjo2/WRPm+QkQu2qCcCOTtK0iyXKW3cOyysayFxEKNJ5s7k9mZLRLA7UpmTaNNQuLu8D2IWjMMvnw8N7kxa6YyZQdJhlrzg8z9Qdm8pp+19jASKRCHFBCZlTWA0G91d2JWpHjAA5/jAsUWYV1sorxshScBp4zOKJ5eRFPgCUzE6Bq0adogRF9CSrgyNveEKfgtk54IQO2iStAVnSPc268jgvPUS1sNiFxwgrr9zYQ4iE9ygJ4flTvLD7mjIU1lTV4hS40J7iHHht1GlxDz5DCRVV3Ln691rLp2P288u6YXjE41QJHOxVHFiQLFQITZVOQnOMoiLH8RlrMl1UzqjiWVP7S+OLqGtbl4iEOAW6e31/P2lW1V6lLsE/bJ+mSjDZrH9QQrJsCPVHQhj1gtdoTGMS2c/3tCqRqvNmuYyEtMfskD9EXIudwscniTjIg2qRBp8VjlJi/7Y8tlK3S/Qlnwhq+osUIpn0b1yoLjmCf9gA/KljfyiW0f36VxN0bcPSEkjGjvYueG+Wh0Ui6SRlaDxVcltH45OIp4128O0ga1bzu62o6OQ9SH2RoYSEk+FAcNQL6qFaQuVfGZ4wXz3aNkQpn1N+RPkS17Za958WnzQbl5WL0yW6l0S3HIrKv65ganS+x3197sQoA6ytMS8ZCWuOeIv6U8D4OqO/0g==
  template:
    metadata:
      name: postgresql-credentials
      namespace: manyfold

