---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: key-base
  namespace: manyfold
spec:
  encryptedData:
    SECRET_KEY_BASE: AgAAnaMznoC/zTAJOZeczJu3HaHwCrHWMkLJZMlYk3jNy5oA4GpzUXR1GWC1KYckbxebqHynEys70SJ82tO/t9daPXFncap5Vw2PHj6ysR2G4tnmvZQVaZRfL+NfqlOuxpeSXM6HHapFIr9D2b0XuNhuupbLZzmXUt5rM+4Nb4r/VauYa7Mmjre/FrnQjvPVLWIRAm/Hr9mBbh1Fg9JK2TFPMa90ZqWipc9NuwizfUVfbjnJ9OyKdgTmYwqgEoqXij2rru8fFCrRz1fqOMlRnpeK3n6fnGKsJ57rblJp+EdZjctTfshzcLI+3sz5aKRSoCGygz4Ed0gqLnGxiEh97KwBIb9Nw2Zp86/veez9A4DG9mE4wLKZjrfHGkXb0ZvURaWoHJGXZfRVcMzobni5TMhVu6RpkddSpYCdWAZHL0EopMdpFK5FapfPZ8sfLNMTf8qFxnas2N4gAzU7IwSRVAem2dkR8AEGurqSATuR/YGPSk4hU8t9By0yNM5ilnDppYoGSKiGOepY8wFb5X6EeD8afgD/LO5Ar+BvEZdvdFPFIHv7UkHwQISW1CKm9cvJQO6zwQH3NEErRWyHEgNmoZdpXgkg7z/IDA1mhP6PrU5mkpitK7/AgVK8+tLGgLmf0jO/TCxJpdJ9GJmoJqx5aS3d2pYZt4AHgUsvTu5yXVkZwP/fw9UN1uIux8RiYlAG/hWLcPz9H+bQhTKBn4q/hzlzVBZi6QaHXXPA5cyO9omUa0e5AYS5JItE3IWudg==
  template:
    metadata:
      name: key-base
      namespace: manyfold
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: manyfold
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAmjm+XFtBTLiataZAHQuxUgayS5Sx+sNo5/dG3GP7DPUJ2EpEgS1IUIyXdYI9L4b5lo3KGS5i+TujWA+7aSudL4KONXx3dMGnJXgIdhPSZZx5bOgltsvUFLCdNO2vPU69qdla4j9h83ZA8XZL3KLAivILafgcS4AR1bF6+B/pNXpIVTUgEgF+x1O69FDB7NijHXu77gQsFC5uXmYlmIYJ54FmDvVssTr39Ji+qT+mzyCrY/5cEp3lHbx7PyCzgV9eoi581yTOmTX/KaJQ7z16yY/VILlPaKPJ/PCBX5Zo/e2z2haU0n6lDlYBfZ+XULzp4393wKNHUC9naKP1q1XBvRQv/DiLsAs9Q9BZJXfRdLKJOXxSaF39D6h4y7H3pnvC++au1XNC0RNrQJmxsWYs+Lza3NpSgTNlezd7CDGC40r7kBoz4n3Wnuy3gq8EI5wWMvadZYpG3R76s5FHwcsXozvfWPtUBLOI/vAjo0EMEN0lz2vramuBQYqB7I+6LpA/HNcORdAU6j+INmN5zNUqfQAtFXZ2vB80R5KTLj8lVoiBhNJ87HU4s0FnI1fDq933G//h01VXs8dUcLTmX5+l2/4pCiiQAgfwjAWWMq37rBZHcDnS2ORENzo7DqyTkmfXdQ6YIB7vVwirb8Zzx5/V3yWxpq91FQann5+muzqwawZ95GKf8DwRFYWic9vtMsaA5KBJYoBbkreXkSzoSpBGiybH//677HnzWtBWWVe2dUufPz3+lupfSUBk3oQ==
    POSTGRES_USER: AgBrIFXJ/iJw2HTBeDjc65yuakV4mm/N/O69rAaa4aTEmwOprJ4d8acoRb9u4uMmo3qgNgrOzNJ4Wkh117N2M+1i+w9DXln7UbXzT5JLC6J1Zl5uHiEu1YLrQA6GRj6ezMVWvJgmGKWJkZlR1cfAVlHb5NI73rvwPsButJ9KAjDM1IvWObm3/o60jQ6j+XEorPYWKOXQMMAE3b2xu4ZrBCxJAhovO2Fhe5xTYyYgkeoRUma33bfgt+OgMHR4knxOcVhpSAzULJNkYX5FTKLXQ25G/5DU7fPJXl4BWlv7skjkiXJJWrFWhi0BIA6qxo9+CvFj8T+whF3T5sMPF/u30Q/LqARC8QvarulR6fWDeA6sjg99itmhGTNnJw+iBX+BuPp0AWhH3oijLTejC1fdz9q8FmuAd17wKEkwY978askXihgLAV2ceRVHok/WaFB1SNgFpSRKZrExoiT/N/qnAYJZ5yYChtIiRDFYHkODg5uM7r25g7nsGaPYTlMpu72XUsxcCe/lrZ5Nb5pCt3Z/Zp90FH2qQi8Ddxh84rp9YQHWTOzZ54ds2cfOV+n+1Ik9dFq6E50vYgKRc0Na+vLoUKONj3P8os5DECYzUTgDwkS22GnGQ9pzaL2UKPxoJMjc+hUcXRndXXCBAlg+G765/BsrdQSaHHk/vyShxJd0p2MCqUuKWcz3bk3pwcFROjBBl7RBV1N7OBVHEZ+e1A==
  template:
    metadata:
      name: postgres-credentials
      namespace: manyfold
