---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt
  namespace: manyfold
spec:
  encryptedData:
    SECRET_KEY_BASE: AgAam0RYPZlrshhfzgg0ttd8vYU2+zhS5/RYTJKo6hRr3SV0gckBZkOYoIXSxGDkqxpqQjjusu0AonmFPU1WfjOY0oCV8PYBs6fv1KinNR7u3zWSHw8cr9NGGClyDSUn8iSGr0mX9+mO/B//XT+qASkltuxo/XSeoXmQp0xzjqrSHnnheaVfYZL4jREvfA4rzi0LREF4iNkLQwEiEuWcB9zR9FLvht07VXrp/99gOrUqUV79m5VOFS6EfHrIJOqZUQ277Ddn2svmT+Xf5QaZrXGvi5wV4pz6XxIb5t46tDqB7T2vOuo9FcfKY0nznHTqjscytJrlIcCQfzrmxOYdeYpNoaFeCTwZIP5Z9/wYH4jGPVcPJW/V1FwzEKP2yzoxo179Vv2BQnHtwlOI8sE3F0AEXlu57WgqFTSsGvXTgRXiG2qSpXrer+2nBmxnfyBJfFdxpuwYIU4NiEf4veHyBPBywltgNkeFY/5jO8U8PvmbEwityNcFnwx9xNd8NUV35kwDfvK5YySQUYhDOQzLYejxO+Uy3p9R3KpEdECT5l74MNWtqOaQpO4mdpPWxpk70sk5tYlVAwFq+JJD7yHWmGa9jojPltUKLPMDQNpTerKB5UoMW8XWDSrwL6SbDXwIUtlhZHUbseEhE8JiUVoBTgmukBOnocdnPvtID0fjxLF3wVJHNtQbvqSI/gXrL0av7MD78REUCTwVh83VHpTSqjKipDITZgKwzDn5d+SDtVTMIH697HfeTid0l2IQ7g==
  template:
    metadata:
      name: jwt
      namespace: manyfold
