---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: key-base
  namespace: manyfold
spec:
  encryptedData:
    SECRET_KEY_BASE: AgAAnaMznoC/zTAJOZeczJu3HaHwCrHWMkLJZMlYk3jNy5oA4GpzUXR1GWC1KYckbxebqHynEys70SJ82tO/t9daPXFncap5Vw2PHj6ysR2G4tnmvZQVaZRfL+NfqlOuxpeSXM6HHapFIr9D2b0XuNhuupbLZzmXUt5rM+4Nb4r/VauYa7Mmjre/FrnQjvPVLWIRAm/Hr9mBbh1Fg9JK2TFPMa90ZqWipc9NuwizfUVfbjnJ9OyKdgTmYwqgEoqXij2rru8fFCrRz1fqOMlRnpeK3n6fnGKsJ57rblJp+EdZjctTfshzcLI+3sz5aKRSoCGygz4Ed0gqLnGxiEh97KwBIb9Nw2Zp86/veez9A4DG9mE4wLKZjrfHGkXb0ZvURaWoHJGXZfRVcMzobni5TMhVu6RpkddSpYCdWAZHL0EopMdpFK5FapfPZ8sfLNMTf8qFxnas2N4gAzU7IwSRVAem2dkR8AEGurqSATuR/YGPSk4hU8t9By0yNM5ilnDppYoGSKiGOepY8wFb5X6EeD8afgD/LO5Ar+BvEZdvdFPFIHv7UkHwQISW1CKm9cvJQO6zwQH3NEErRWyHEgNmoZdpXgkg7z/IDA1mhP6PrU5mkpitK7/AgVK8+tLGgLmf0jO/TCxJpdJ9GJmoJqx5aS3d2pYZt4AHgUsvTu5yXVkZwP/fw9UN1uIux8RiYlAG/hWLcPz9H+bQhTKBn4q/hzlzVBZi6QaHXXPA5cyO9omUa0e5AYS5JItE3IWudg==
  template:
    metadata:
      name: key-base
      namespace: manyfold