---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: key-base
  namespace: manyfold
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    SECRET_KEY_BASE: AgCen8XzaioMnIhYzOoB3DKRuc1PWg6QNc4ykkNV+5A0K4TNPYvzcdwMZtbXr/ZYeb65PMGa17+Com0kkUR0IoZUQU2kGUFms4YAOzNyxPIxJa3kbDZ3LJCyHzx5Mgh2fv6e27Lc3uwknOcDOR2FzWGmWYY47BnQAj8W7OWGTX4YyUzXziN31Eh+X6Ojt9ESbM/sKsyxaEKm6rLPKxC1dLML1hkljWqTTx1arFQtZC8QzNMgjcZljZCCnVMFPx48ges6JOB3DFuF6Sd2bsSa3fRYYM/ScvhSk8p/cMkmh6zbYxqAIF5rRxXKlDz/hhDqIlujNyig51VatOHmSe80zftLwrBtnGPOvFT1tkOC6FsaPCGQee0FxlpXKRGImpnXcqrilcfSwK+Udj6x5Wh8aZ6JaO/iuSfaaGJ8qYvwUBfr9iAwhl9cnTbrMuoyYRic9FIxQlnlfzWBqOu0mPVNzHOubThlDFh2AX6J/w5/XOsdFiv17YQhKuqUlG0SHcmQEtO3wBdcqxytTagr0tHp3kKPPiT1oP/gndBvor59ZoT3tCLPK07IEjWRDMwgxVCWC7bNXOymHg18zjAcX+LipAN6WuQh/3PG0GbbKmkZNSS0wGT/8qdbtM2JmrMQ1AWP+LGftTRuHp26w8xfeG4M21OoEFEp3D0chp5n3yncIRhIMT7OAExNQ2IB7Qf6b7my82SP+HJG0P41N5TcUlR9eVos5Wghh72sqlBMj/g1YUv2Az5RPogbl04CVjELsw==
  template:
    metadata:
      name: key-base
      namespace: manyfold
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: manyfold
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAxaHw41/uw1qyN8sHR89ecqnaLUPKyg6eJMHil1SwLsNFS7HHfZ61sL0lfxo3Oz/2YxU1vOAGJcxN0KKxC2q4F3i6QRFa+wIJsdcs1tAZ5jpnwWPFHyoaWwBNUP370g/d3AuDqRKZH/Hbb/hY3S4gshA50wp+xNQPUo9OaJD2csjhroE8Yrtm3n/qGj6ef0fC5asvve2gfzTDgR4sjmHbic2uqY/48fDGvAeWTTl5nh4MsdQlRprZpl0lTjJR2EpBnFbapsBQyyGY0okCJB4N/zox8BOhzN0VBjq0+ayBhy1ggqgCt6UDbAvgRpbO4sdNyLiFM8gn4r9nwU1B7TPwzu7kNRdpY1TXbPWgPP7dnL0VZTJYtg6F3B0rkSMlAT3Un45KUmNHQqQjVLpkmQS1QIf7k+6nfkS3ptF003L570blWeLkLzJNz0iu0a+CxOZ//gY00A9kA+FjEADfKNAjJ0RQwfjwJmw3TL1y9Q6N4Cq/fhretCLomd+pkml0QrdYhmiFXgH5xj3Dqu55mYyHot0vpu3dpCVgaPQdCkwGP0b4lyt6rMhwmEf3qcG8MVt0ZsLVzp/gLNCrfTUc5/Yk5Sew2XOzLCBlSJXKVdiJ3pxADS858oZPja1xN8o69jKywE1Kl6tm8OD29o6abn4gmtQHaBvYKDUz/to+XiTWNO14bIhDjnQY4JWo0L2sOhESd99qrwvEb1yrv6g9Ql7PMuEN34ohSmX1qo5YWtC6MKBaSgyneKQAq8+xfbUadtZFIEYkQAMdVjT1XuLnI7hTB
    POSTGRES_USER: AgCcswgG+xYSp/q5RhQczMGURwQ4NHwuDqBvmybpWl9YZqPQYIxLpK7EOJPAi+8QfPmJT8FnKsPncXtLljnEGbP7V7DCd+oHoaX8f0MHrY5rtq8sBxySm4UlOK/9agn546wdBGfGVF48Y64qGudtn4UKgsLtoHwrB+OAhLteTIgOD/92jXJdCV3g9+1xZdSfDvyVjZdVzryJSjS1A7TKepm8Ek6zQSMyt3aqmXowm2g49EyjEBmRatrZqD/2DUdjv7ENbtzW58/uU4yNtBZjrHXxASQepSz704xtmSH1wQ9h3H+S966grKXaCpx2uS7U0vXuCo2ic6EGSFw2ODTuf9+wSS/Ah4pe03VLqI8KSxqe8Bm5+NeLGsRrDZe30zpoiW+rbdhWHAp5lP9OTRs2Ei1vya8NFAtYNTL5J1CsYltwtvGeuMkE50bRMAahiCcdBeFjMrR2rMwGGRxBl0rA+N3SkUjfzvxQVWqKNuoaP5InPl5SuSt3o7xc+cB9ezQsS1rsdwLHoPdP/sL78ZnjZkUMkF4sWRKD6mwdMSq4e2j2/Ahe1HU8BQt9GxegviQnpxXL+xk9dfZzM+l4icAr8dpMHohg6YE1ria9ywxuUMGr5q1YnZyMUyp1wXjSU05QISEpJ6Zm+522bgRLYOrOIVpOczt3TlgP5+hiw8ekHiixwsL7LQp5QS1kQ+05tpsoLH15O5FuMw==
  template:
    metadata:
      name: postgresql-credentials
      namespace: manyfold
