apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkord-data
  namespace: sharkord
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
