---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    rootPassword: AgCnsUcvp52Jx+yQDD8a6kJnPy2lcMomA2KDj/yh1x94PlrSuPtmFjzkufp4RBiEjVdDCjzn+qo5oz4drr8VsGYANx4M5qPIR30yAfYtr+w/BezwmPOf1pNFi47U5TAYNuPzor+y7GXu6n+ZjLNsuHYX5SVz6l4abGQsKDua0mborN1X9/qOY5PUStHXCDXLis2btaTZV2yiK5cJyzBM6yS0A+LlC4SIswR/ZmtLdcDh2pY5MSdknrV96ZvszKCtWi5OLHFwAiWGRARFjFU+8QnavyF8KtgHV5cyvCMQYfTs0A6/P0T6DLKTnSbHhEWwq4WIFrRkaNLQYRAlvWb6r2oLKKFVRt8ovlcsx/8P4T/ZZwjQ100tZ21qZWbKdRTBwgZUnX5QEeJ24udooHpQ3Cdj5vgVcVI5n+38D+i2tJdqSuVRYq+H15uRla16Cjyiklv15RmEdcinkTWZVHUjVAIHKBxmSouG9MO13WgU//zJYldugfcEv3p5rN3HWY2845hA8s/G2IOvrIxfmly29PbDArc94J3YzbCE6wXvibtbLrSQ9PUAEqgvTPP8n8jK3i4qm+ipa6hQP4WZ1vvsMVW66/J9iEq68PoY9EDHcFU8mY5M1qeQvjSx1aTCfRfjNjeGR1TZDeyFgXdeKxSoq0ChMfV/P90dYa3Ny6+6pw8QUzoa1Y4TZblTIWnXIk1yLVlhnERaheiVAWZ+cw==
    rootUser: AgByGCiBLESo7JNzxCB644qksRS9GZc3RfhhS/ucRelWcuDIDZ3dPHuJgsoYPoeKtIYHvvS8Usaq2iTotophHwL6ncUvcdjbD3HcJYVmLoy6qdGRjGTxlzEFNr4YKOdvAzzxoZoIqCOcW1zaVKn+swgDTu6nkSaZEW4JHZKLbzXtQ+aAgari6LgidlzV8bubmnj9q65+4OFwI5tSDoGBQ3ejKGp8r0K9NnOuKULFoTVY2PQuNTOVcOJriovB8ICUnD3ePnvjlrYDRfjFl5yfuPI0shotbw8WQS7qIpZNwv1OEW5hs+MnLCGm9NESn8i/VCjInIF94LGw0PSuH28OmyhRAzYYC+gl2J/tAovK9oqpKIMjViZEi1aBM2JptFzm6nx+wb0NYYyzJGN+G2mNiV41a4dtvG8Q/AHw4LXSCjkoGBa/Sf51Ns61FM9F467A3RwF5XUGhCGzhE8R5/yLGqPjiDvWBLwIrgI1tba26JX8AUQq6FZ328UIVd166QKnSJzl1WVHyu94b8euB3bd1wXR6M6GXdzfRrJSI/MmBXSBgezZWphCYmpQEverE8kIJ9fmXQB7W6KNPp0peiAge/VjpTvL7o7lrC0/5HeBXSL+rkhtU0LkJ8mGhEw1DSNbgVyIXixW2uvAFS2qwJx5r+PDqP2/tf1jwvxN0ZnhNSsOR3L9W+QkvUUbLvBPBrrsJjuGq4pSGA==
  template:
    metadata:
      name: minio-credentials
      namespace: minio