---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: gitlab
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAjO1o09mxO1RsasstH5byCXEOhObvPi7amMAKohOQH24aycv6wpAf99zQcTDUUkB6RvLZmMDDnR/coD7WA3tMqkW1JuKNCMnj8oVjzEiAwnCGk6JkrZx9khjpqbJFJz1gRt70SJ+G08wztFa2KHDON64ueX1xRc66bzl/pk/tRK9Wjobx9CnhaTxBlBaiTVj45y1MJ12TqiMt2YG/MofKd1xmrS1cMAm2RGw2TkuLsc3XBN/h7hTyB/kITTiZ0nJ5sMs/aeoCDXRtPICpoP7N6xyeG7+s6fs/Nmxb/OpIYKkAht/pHue+UPsViRvT/+LCVV0QHJSfVQMGtuSnTD5T5dVtqbWlSVCsjcV02kP1CqBtGzlay39tr1cTNcu6be34HLHXKn/L50oexx1yjzj4T0m7gX/qVSHlZWDyF2lAKgysrehXJjof2apjw0uDzcypbXlBpwxZZkFPqElMb5kKED7jTmJQWnVKeDZFiJbLa9p69J84RSDs11EvvvH6kHtQoy3iBDUMWUyP3t/ifnuNfZ3giOGZ7bMNHv0XrRNlCtBcuhet+8HwsRGbkw8/razEnLaaT0zu3+mNWYzP/DEhKOf3c/NBiXa1uj/ej/touI7XM5Tt8IzyMqQsyrn0hxTW+jurvIGyF0Y62xCSuE8h40qPGaqJqLIaQQPrSdHD1u/WdlSA/3pzMi0pNf4aQm/4HxSKjvP1CWlaIV/8Mgd+b6NJAZRbHNAvMefhm7YOfGj6YTEQaYpy/wgJaHKfXRJLJOucKXBOyd6QGB6Wv9hGC
    POSTGRES_USER: AgCswFoZ6RswYC18YoEezj5arLfyGMtFIL1ZXbDmy0orJS8RFtDqzu8/OnWqkPOnxm3laRHQPmWs+BctWMwRGQUbpquwiqkumLV5w9CDhsvvkV6F06HWyY4+aILQ4/Klr1S3hWCo3aggjZ9Y6q6XtB4I6D4M0DpnXvRC5ulMzIvQISECIkJ9uF5h/ZWHxXdGvOXg7l2DnDJYC44knUI8/Oyj3CzqRLO5OSy3mx9Q0hUNGf5KYGr/mQbQ2AlXA4glKxtajoI7lbtQQ4Vyr6N1FIzcJ7wz3esiMHTlzSZu9+SvM/x6XMdIp4LBRO5crRTEC6lgUS/Ax4uzDeGdUPUY3kZcbxmyUfaQNA6eMdbmpBT5yXweYG9Lvn2L0hJxgKhhUbg3JyLO7CiJYXnPG1Di1OGFUMQNDd9+gz+OICdmni2D1pQAwjr1PZbnV902I3MUU6zzLaH+ifsVgQk4LF6YejMNE3H7mBBS+/EMQwSd+baFuMPKYRAGEypH1zYANpCwYt5l/eBE03GBWZBuVOK852Eynyvl7et79vzubm2HqVyUXQgvLRb4TlxNgoWCt0/JZgO0T11NKnPza3cYqcIKxdIcfj28pn0c6fV/0itD0/Q7dUIZsHxbL8i8kULymws0hAM38erPoqa00YxOxst9gCrhsaSrb1WZm2+BVwyHIH7LEK14p5nHBqMVieXI5NzAYFnzOdVhhw==
  template:
    metadata:
      name: postgresql-credentials
      namespace: gitlab
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-storage-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgB3/Pri+LmDuGrSZMhYTzU4r8uTvZwAZAP20r3bxocXG7ZmcaKeaBb0tg74DYh4K6oU+VrgxSrbG5i4cOfPTBU4FRab53FaQ191JNLDNQlDvdn3ZHvi33qCbXBYX9vnMCKn/m4xns9AWhhYYBCbtM7ImGCOqyA05MQgPTE2a+BKExHA3XHlTCZ2oWuvYlk8pBgbDEHGnpWQbgUjPF3+EdoiDSuBtHoz/Uy9/qty3i1nBP+vt1T9ZLB6MalXRAg/u+wDnlioY84Q+jFtZ65gm8DIw0WVbnswWtTBn0yg4HVgIt7ftKA0/gW9Tv+l+ps3MC/PZ0HBeLIvH4zzahb7xI7fVpbcKmmiMbgPNtMJPXi1byo6GGhFJ/S8opsAUcLVOzAjJ6b+fEUBWErVatObSQ8WGXNlCSRmfk/QxEp6u8MJwsOj9uGhla5iOmQ3rbEBe2tw3LkroskqUpJCfvAPnqaOpi9e9F/r6qzUdc32cG3cT8dOk28a4r5PS9VkKo/Rl4UO/SutiMK0KrMA283W6ffUwJXYeBvvQPvU/6R3xBj3qamg0BQT4PyyCiKZB96gDRW0XqpCf+5zOh4zhhCA4krEBVXZCm+yDOP6jrB2ZDhvXqkw1LdGMb38t+6M7AV5m7d7SKR85+ol4zG3EFDVfCdmHNU+r3tNbneuBR32AvfaIGiNrm/cNlK+YnynJEncMS2RGpgfewqfZ+QLCxXJu80ueyZOAF4/UWLqm3PgER48ZmbnIAa1dp9BnTokHy+NGQ3uz7lI3gN9rWY0TptNXdgXCbauMwqBJ7OTe71LO+6X3GPg0eNnyHsPv+grbW0XdLxTZv/LujZP4Y/zX4u8k5YDMwUX1ybj9AlcT4Tzng4hZkgzRrUMMG33vXV02kVfcj26PpuNNS9YmCjbeWPJCnJy7kei4t3kvsUMiGf7NemAtU+oqf/H0Vi30PrgdI+4cg3EwS+stV/X/s7uIraZ1Gc6mXBsXoq4G7FuqPK+6D2QK0bre0fdQEAljWYA4rmWgY2kiDYHvTWVw/xssw4ZQ417cGBft3Roo2sOQsJnT14=
  template:
    metadata:
      name: gitlab-storage-connection
      namespace: gitlab
    type: Opaque
