---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-token
  namespace: media
spec:
  encryptedData:
    DISCORD__TOKEN: AgAsig2Se52Db1GctQ7nnMLaoDMPXdybjaZ9vCNuzVAADvG+OVPuZ7VtixyLaZ/PrXl31t02Dabr47Vd141oMJdZEsqRRTrHzoz7aqTEPM+hoI23jZBQXGCcefuWPRLbnmbYZq20FDwulnnAXtjJgNt+8bYw10u8Nb+/1QMJUMmDFUCk1nwqH3pXZkvqoezdPynUssM98AMBREAhy9SZ+re/SsO+R4Rj/1asMN0oVfuMPnxwa+XM9H3qcFoZJnjPNwtTNMQHe7tStp0hVVcdQNyW3CyLl7l2wQVCH1E5z0aN60A+4GFjIPOLX0IKedbzioGc4ktJp+PH+ObQqWzU3/+yTNVNCnZ7sU0RkVcCsauRQ0ZwTKCXDjHsfqEs6PpzTfAL86eXe8pw/bC1jZXCs68XAb1c6asZXu4pOut9V0CgsKzovlobzty4fdWrDerVH4aaNiMsdShmmXOw+bHMzDH97RlINhRKZ+aKsZpSQ1fnC66gfFd+n3v1rLUfVbmILuumkEb1Q483Nnw2bdXFjXGwt6vp0hVmQu0s7sqOKPTlDNSWNtVYSTxXVugqFaX+OtHBkbC0GbeHEbZFqZ/K1Rs2KxifJ5BsK1qiHlJHfgnAIjmZ37zldkhz13MLwhic5jNsGMjYO9fifOJZtF8ZFfrNU5kR5P7f/+JG8G0nOkI/k10oHga+JXFMR9mYLN1CY59vUV0hfUpjLkDUvNC1/cSnqlXHQOZnX23W61svcgo8hSzw4KnBIcxK0/AuEiEeT5zxttCmlAZk1G03xr4KqzHdtX2hvVP/jjA=
  template:
    metadata:
      name: discord-token
      namespace: media
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seerr-token
  namespace: media
spec:
  encryptedData:
    SEERR__API: AgCQxykHZX2xD92IQET8Ma6jeMa3YZadK2Gtp4G2uas9QwXVxfOoG49RLYBL5QSt0IucSzkIQ71UKrdURCx3srbx++nY2thYOhhXcCYVtmir2KFSmy9aVAOcuHZHeSmVatR8Dvrt6AkuZLBpqMgIepIh6YL9mGykg8vhYkshED6sBweZZ7Pm9l3b0dFcuGun9/QwP7e1jPR1dCSPH5tIPFowcA2fBQj+J2fiU8OgqUEFMVOF/Zucz1v1P2WT1t1x7kjWUQluvFiFa94dqg2TDSgtfyc4gbunzTum1T/PHcYVBrPmTqyhi66FrbEyxrthEvuQ9/XPwPrVn3dIyWJOhPcCivepIAhCFLl0JpDxQ76JgmI4a+tDQ35aS9rJqNi+NocJyDWBUcR8nIfepFhJxZ7eJrZ2ocaer6Fx5uT6wsYKX7n7Q5SVyNt+QsnWvKYNoKFw4f+ZAAA3OQ7oGi+dNu8Bcx1yOhqOXPECBKH0IzzJS0ptjU0EaBk1HDHYGR03rNkTZYCSwDSkf4ZhQjB+0AkKk4kkTqH8JanwA14M3CFvKdosRiWnpGeYmhuK3jYadqQHYKxMWaLfHSd5ax7pxNAXMbCS82oYO1EsbGgzdD4FBFtEGMiOTgCVI/c2aK97nEb0lr+hfl3DLJb7eljDZvCj5MrSxogaAc0c9IsO8+0wkBst690G0k9l9UwE39ASln5vXjGVSEwpLE91oK5HhxmKBmD3I+ZtaaGtXjXD51CDYta/ok/qGPcoT+ZEfXfRq4EQkwjeyuEl4p4ZW7NUjHvn9T5LlQ==
  template:
    metadata:
      name: seerr-token
      namespace: media