apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: sonarqube
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCWb1eckcYUuqwNUvAHnZ2ZDwikAGmbSGJ0sCyZOekkcdao5nz45tFX/7GZYqTz513VMaqUt4NHN5sR0XhKurdVmnA5LI+0afcb2x3azxkLsAtPsLLeaLK7008Ah/ZbeQhZ7EHH31zA7yG4FPb2cwATiQ4rok0qGeT4WXWnPQ1C5FiVneaiIRgYSM4a1H3jfZPmCYOUZyz5WLngIF8aLyTPaznch21l+R2ZjzQnTA/k516F0nwg6RtD4NnAtgnWnSCjFuTkxJgZNk7QAOMIbqbJDOE36uMaq8lrlfKOQmh/yM3s0xPqfP7Z1uQuIrx0tKz1b8uFLzCPADk0yu0w1/TkxMRy7aKsEjHdnegunAQY0uCQ4xujh56dsSAg00dV8o/RdQf5k+mKWq1zpLW7bwWngAflEfXU6dWq3sQjsAtfq7gPE+5oLm5NmdyUhCxJNlhlgu89T1z29fMphV7r3ZaFxd+t7/WIIKKFY6uXNYt7E0DGW2eMfqk9jXkk8DyWbGbP/jrOMkxfVVVzmt4GTa+9xB8xAo70aONfu/0pklPH5sP9UW7ha2mPEkRB8ZHPP7GNEVTSOQigjeFqYqFwRqYRvIZVum7u4X/lJz2McVaIDYhidl7j8eD54adSjNUFmYwzqPFQ0wxv9P/Eh5BOvK5FVfMkXviN5IAbRIF6CZ9Stx9qz1ETARFB7YuXHyTZgw2a1ogLCGeMJ6IlNNf/PlFhCI8qplmm8Dws+6PMwzTc9g==
    POSTGRES_USER: AgAinHMN22zUZ31QC1I2BYW4i76VCUnxlRH73+fja8i+a9KMreXYMINgpeBB70+Ji2RmC4z96Uaoyd9ihJFg0pK1pcfEpI20F0VxoY/B4uHYo/LnDxGndYWeLTPAHL9q3gWCzgX4cM6ljZZYMfRMSVZZQEb9mqeWdM7fwZ8jShaR5/qJFmgsG9icivDd4POTf+DE1cAhCfs90hHQeqW/g2pYzLEXvyvhuAZQQIxubYSUKv/cQVO3RpslWtW2a7W57eaJgMEN3/IBw6EbKvG0SYsenqA82jnJdLn0IkJaiWG2VzT9P7pct7nabS14RUTeIZoyQtpyXtYV9QRxw1dV7sFEzCoZmpBZkQ0lglcy3Ig4favze2TgMCZorWsqEkbpF6MzXsp8OvKCDE32/r3mmT6ev87ViAJUmc0ihJjDifgbxAhRyqLxGpvMl2potBvR3qDFxooCP3rByQfZOiCMGFO4wv3wsG1SAyKbeWflqIYr+IHj3CS8+llUQt3mxqCslryDByQT5VAqvqizdV9SXCMujTeJ4Hi72l7TkF0JnBoPsaaIgEGXt22Md0KDZFqsnzybaCKZG0DAnbXFJP6NpXIzKxWM4/MMDNQKAb91tcggiSzuehgUTDzEMCQxZ2VqQdbriHEUP8agll8wMWpF5O3tpBVoOu1w52jWcgEAuip6RgjYzoNpji97cplvxNYKErxWn4/Feg==
  template:
    metadata:
      name: postgresql-credentials
      namespace: sonarqube

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-creds
  namespace: sonarqube
spec:
  encryptedData:
    monitoringPasscode: AgCPVPw/ZtbrIZZdAUDpIxIJWPwv621WL/K1U6Na6DSx5ul7EIh7HOqNJQ+9P2cZhixXVtmq7VOSsVeLOprdiXnUh+iY7RihPkxRz36sEmXy+09Nw7F/mI+RiaOFAGun6IdTT6pJSvwKgTObI3acdS7/hEPGs2kLsoY0edEC5igIrE3JZok2Xez1MBmEHJTfHkMqIaPUjGBZ76Bl6DhtgTpoUziXDe/kOC4q28RWYJJ6pWoT1QnnS2EfvasOZ/ZoXdDumXQZXqOC2YHVrdrJFiiE0I3dWG+booizR4KAqlMnFY7XhFSK2IjoVgjcnEgJ+7RuboOV8HaAZCasY3atjAKIKPh0zkbQekIcMa+orT0WZNAfOPe7zIRswDU653ntP1YcV+aTDUlPruxMUNkBIR7io87jBcewaDz8sRKmt7hTOOioUL1xpggmxEYmzhISS3O/wl5n7BSiyIeAVaTGJd2yBoyo8OIz43KIvIwYPDkZhao7irz9lLQgaWLMs2X4p/i3ekcRaNJIxyzf71dywys1i8VYelBxxMN3bE+AB8SCHzXXLtlqMaGCDm27+y5TpTWszpQO5EmdqI0McoCmFRUfWgXuC7y7eu/jJKX+Q7HSAqr55dZTDdQZOLGGKlj6/pctPLbc3HbS19jkxZE98Xaj0tokCJAKav9wA0UCCTamN8vQPKWRKpjQ4drFe8/YUN8tTnK8ktFrtGq/3gG4Rrxy8y9l6O4CMLJwnzXuCTFn+A==
  template:
    metadata:
      name: monitoring-creds
      namespace: sonarqube
