apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: sonarqube
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBuCLPiXniY5qTC2CcOUEU37f/R6VIBxFOYtL8gnoHcMOrdtZDBo8pe5lPQBeDw1wQH+QkCqFJUzByzCrQDtRM4JHVWzmGBo7kA4gLNDl2oIfc3IkbeDp5Y5ci99t8r2dlPtar0NsS9fbvZxVvvUZcJ04KZQTEGrrubkjJBfAmwNU3e23NjF0rjLewGqrIXVUoUZWwBrC8enPTHIbn0Wtq0+nwUQbdpwSs8bqGigMg34J2IvBMSQhUIXqs3daUGSOQBvPvj6c4rjD6k0xGeVgxgjzSu7eHPdbeOGl8QCYuNkD2F9cSUOrTV2Hq1Oa4DHGHbGwyYB/r4zrtvivPDsWdP1/bpJL8UzRuz1OBLIAAW+GmOvmAc5prHBVCrUObAUlVmy+pSVLjofxztbFj2Y3/GXkH97zanfyiNutzTa1EOJ3OYJNtmQ/ccZTxEYERTztyNu78UHQA8qVI2JUIaSp52z6kKUN8yepqp16Yu/tn9p0yFIuhHp2rupo/rXgQK6D77UBir769I/C9VIdWGK8Lc8qc/JJgc0I+9tew3U4SIMJy++UzLOwoUQjSly3vYnjhKP/glvrNOJQDKkuAXmVF/hoOsJC2cb2/iQ1du90d/AaamT990vXr3NX8N5b4Yvhd+0Gp6NPEY/alvHdJw+5GqKBhdD6YKYocbdIrfNU1jgikQZVP32Z0rXGHppY2bHjXuIu1g7ygqopeRFw7QcxnP2DqVKopBhtBWz4+cyJFz2Q==
    POSTGRES_USER: AgBbs6rCT0JExKEdVBnuaqlpvftO9K9jEuAJ2GNk/E/6TYBv21TX/sS0fUWHFyIlkfWrRgdF4Dt5Mcz5M5K/rD0q59beQTCghLT0HSItwRJA++V3wNoKMV+5L0hK7DUWM73cIO/4VychJVCCjFPjId4Z7M6PwIoxCk8DKsDuShmXeFaTR0iuhZFXaRK+opBXTiv6UOpItM42HLbF/5MkUNGeChmzBh9P4XEg4QBcvVajZCdpXXjcpcGyyHy7+ePvP2/NI25c3rOeGZAHm+iqzXmvShrWBT5mQyr6JcF6ppHMYWMxQYroS+FKyHUMRn5mFbdmhGFHnio4EFAFhq9hTkwaBjJkeXB/6fb0vKBHNZkhL9EQ3YqMktswdFCT4CjlppGLpBRP9yrQRw/KK4q3hQ9rtlORIxtS+a3lRuuM96qWe4W/6zvumrSaz028j5XLpjWURH8xPuSqyaHDXDJbZ99l8AE2q6v1Cn3vonwOR+Evdn6CRGlm0eKjLhsqjLy1YSlH1o1D9GWHWdZ2Z4eIgVj/BiV2O++/TcYtcCKSNbrsmUFDA2VudKkUyrFOjoRZh6zZe7kz6GVPZJah5bbHTbM4/GckhcUGIQ4ya4+Z9yajfHUTtccj70B1vSetnM7I1ujF/1B8XBF1+a4muJd3bLYi6gsqj+YeHQdtNrBHYd9/Oybncb1ydt8om9whvFULMK5+ccgSnEYn/ijaF7aIizLjikCcTyRNGqPZynSa0Ul60w==
  template:
    metadata:
      name: postgresql-credentials
      namespace: sonarqube
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-creds
  namespace: sonarqube
spec:
  encryptedData:
    monitoringPasscode: AgCPVPw/ZtbrIZZdAUDpIxIJWPwv621WL/K1U6Na6DSx5ul7EIh7HOqNJQ+9P2cZhixXVtmq7VOSsVeLOprdiXnUh+iY7RihPkxRz36sEmXy+09Nw7F/mI+RiaOFAGun6IdTT6pJSvwKgTObI3acdS7/hEPGs2kLsoY0edEC5igIrE3JZok2Xez1MBmEHJTfHkMqIaPUjGBZ76Bl6DhtgTpoUziXDe/kOC4q28RWYJJ6pWoT1QnnS2EfvasOZ/ZoXdDumXQZXqOC2YHVrdrJFiiE0I3dWG+booizR4KAqlMnFY7XhFSK2IjoVgjcnEgJ+7RuboOV8HaAZCasY3atjAKIKPh0zkbQekIcMa+orT0WZNAfOPe7zIRswDU653ntP1YcV+aTDUlPruxMUNkBIR7io87jBcewaDz8sRKmt7hTOOioUL1xpggmxEYmzhISS3O/wl5n7BSiyIeAVaTGJd2yBoyo8OIz43KIvIwYPDkZhao7irz9lLQgaWLMs2X4p/i3ekcRaNJIxyzf71dywys1i8VYelBxxMN3bE+AB8SCHzXXLtlqMaGCDm27+y5TpTWszpQO5EmdqI0McoCmFRUfWgXuC7y7eu/jJKX+Q7HSAqr55dZTDdQZOLGGKlj6/pctPLbc3HbS19jkxZE98Xaj0tokCJAKav9wA0UCCTamN8vQPKWRKpjQ4drFe8/YUN8tTnK8ktFrtGq/3gG4Rrxy8y9l6O4CMLJwnzXuCTFn+A==
  template:
    metadata:
      name: monitoring-creds
      namespace: sonarqube
