community:
  enabled: true
monitoringPasscodeSecretName: "monitoring-creds"
monitoringPasscodeSecretKey: "monitoringPasscode"

jdbcOverwrite:
  jdbcUrl: "jdbc:postgresql://postgresql.sonarqube.svc.cluster.local:5432/sonarqube"
  jdbcUsername: "sq-pg"
  jdbcSecretName: "postgresql-credentials"
  jdbcSecretPasswordKey: "POSTGRES_PASSWORD"