apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firecrawl-auth-key
  namespace: firecrawl
spec:
  encryptedData:
    BULL_AUTH_KEY: AgAaBmRsqy/Qt92u8qMetJgTZVAwfrMmCm4EcxTAe5IqJa0qGMuySUi1ilnGfhIGYHOySyWiINsfnMWDeqrq0wYqVNyF3eww57llS1HoXE+Ow8LrhxVsFb/3cRZ9OaQdM1BrTFPOj8kEGWzI8pXmemQQ1/TCbsOUWFD8gEX8I1G3/ixe3ZdjOt/duGjHl7AlqP1uqyNjm/f0Q8Y/TQinI/1dPWSMlXvUV1LVsi/Zeu99gA7W0b6TBLaQ2AueyFoeXBmP/Ix7eWn8HdpQH118EGZlh09ai/T2s8N3tl4iI9OoziMlQewpqcod6m7gzkZ4yKOzq5kmplZP98fTuMEQP3aiUHSX5q+mC8PuGhMrn8qTCB3UV9k6Ojj/PwMN/YkHIeIdLE7rneIxMdZ/oFd87rBM5IeOLrVJ46b3HcECRo5b/afZiy6OeR3eQ1KQAj93/yMSfGeEDHFWccUjmddTyNp/jv5naL2XjLpWixMcb4eCOCXmIk9EeNuf0gUxWimNdDGMdI9Nks7wTguDq5HopaW0ll9MnEzwIx1zA4S0z6c03FRoQQ5hstV2FuD9ATAlbSohmigVM6RpbP2A+gX84ufF14oKIC/BwgN4ArHt3m6UmU3iCtVa95Z8y4/IesayKKRKP1JtKkD0HqB101apDT/4x9dEXJMbWbdgD3fjaV9D9z1/RLFS/ZG/KySDleX6f0t3upGw6hDzPgkFcyQ/OL53U3IZwudJBjmGiKqb86dUnk7CEM4flE7FwdAcYyq8Wg+sDP/Y9l8MP9VrHdBmm1cY
  template:
    metadata:
      name: firecrawl-auth-key
      namespace: firecrawl