apiVersion: v1
kind: Service
metadata:
  name: firecrawl-lb
  namespace: firecrawl
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
spec:
  type: LoadBalancer
  selector:
    app: firecrawl-api
  ports:
    - port: 3002
      targetPort: 3002