apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    adminPassword: AgBETHA3N8YIxP5mlHVeuNYUjqon79HBz5VeEnaeCBinQIGEKiGYuImzXG0AIkk4tAsOGoNaXKCAAaBIXrtYymnRydhJg73YlQSf6Mv9JrUJorEFeoQde9itZiHuWDWpJpJZUhmppxEIAJ68S3NMfqGyhPCv4dI1Lo12JznLjChnfHXps9p6iXDbD/WhK86XZgqJbvNb3a0p5KnDUZ30vwQG+cNYRT0au5KmcUpS4RY3OQKY62f2jqGs14uGYtqJmno9liusU1beNn49sRwJhel0wYcMubof+6U4jSpXm/1DnhzPNhOlT4kwS1krNWasDz0/p0xLj0biLyUWhWuuHLolcbHPDbmhzYRsmlmF3uVQV5vXR3029NqXaCtwiWO4vrTHY5ZdBLG37eWbptocsuwdC6CSmx7FcprGRFvs9QQ605S4eMFHyiO2NUzPufGedvvCnLg+f8+MAZdgJ/PkzgKjno2y3NapFaSrP4G4PVvBTRDsRLyiVdnTM7VIJMaTMtDcWB14JLWhA+x74iXNA96wc6FDTaf313pIJ0LNnA6i2sa6t1nYHO63we1uNIAPcZikfob9zSuriT/0wA5i1Axh63OW1QqsHxqVYe3DBuhgVejiNs9JOEvHY3YO4fbtOr4aVwc3RLCQZzlak9yim3ploZMICsHSxoA0dAS1CKoMdjwnatx+27iYcXH76k7OAk1EheK/Ll6jIGLQ
    adminUser: AgBFatp+DSpsvH6mr8m9nq162i4tKwqEKeFloQ/0Z7eEt/uBNwvK+x00Ceaj6RfSkI4DEeh7qusecUz2j1Ct7cpMQeaG+oC69e9l0W1BYk0uBezeRkrkeIttYGUiVlr/sKGe00bI7Tuo0kiHz4vxCCv4r3FEXAKusuIjCWrgfxCwTRrjV8mQ2raczWwqmZgVcV93oigLZwxg3JOUMkPP7vQp36Sbd2duZJB7MFTTuZwVsilD2C6fHjY/zyio3uyrMW0ikWOAEPvgL/1hZIxAh1k2Z1xETKDOlKY/EjHVYAocr9stCgYDct+NvfMmDAG0SjUzHkE4t4bkMC+9dV9N7vhnUV2xX9yCupFr+0vnbmb5LUpISZ1+epzmwzGGu0MIAu23EoFHd8hR107Ufb2AYMu16cEZmzWoGXZ0rhY1aYAJEafaKZ0eSoKb89D9IV/e24vY5ZzpJUkr3RlMoVMdtUa3/5kQUmf3WHUFVktJDum1pjpQX6CdJSg6xmjYn74hiBbljU6dtStat3bZLyBXH9r+hH/+Tu420exD0mB4R1RDJviZOvg6eFKROHjgSGWiXEByE5X6fpr21BHHHihagLl3WS9uP36i9dbjBKTGaFUAvTB9/SqGcd7CBbBHyN6j8VaxVWog9XdteWEFQSyCR6LTTNAdz0/2yZ+9GX2/s5olcMBoZQk1rJAAm794RGaSlQbaSJOr1Q==
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring