---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-claim
  namespace: media
spec:
  encryptedData:
    PLEX_CLAIM: AgAEqN/xO8w3PYVVmd5dWuWqIRjLgMRLqUje1xQCwaZSitTJKnR0Xh1Nb7CqPzQvfDy8MUwDd1dWsbI533Z4ZATeKe3nuktvTDE3wNeb2X5UXP8SA2HCl/ij9SFlv2QKA5eAkXmHa4uFYalqLqKcdvWKbhfn6IdtISPYEVrThOwlKpD4x0N1gh+CJmdkoWWyqtGTqmwNsuJa3YAt0YULWqqlYhR340zMGI7FT3e2i8MC+u1YLBC10UNafoSs42jtI9UhL5MObY8XVTCq0zhh5ajHwCJN3c6iJ4bc6F/PUo+RY72T6GPQYflC7Rn9X1A1C4nt6Dg3Mn6L6c45ORYv2+fk5GOc36DRvkChzpUmGaOM8XL7hLcQygxU6REcL0ESWgsdv2ERHKJa1c9+dZO3jvi0664A+MNM8xvm6hSB59Uk3iVNdjfBk84mLV9bXNu/83tI0U/427hIbIBcgUTgnuzlt3p0K7UlHRljfmbgTIQ846k57hvLfFNIOn2GHjp2dDDWHtMApRAAeFQ/lB27YaPXpqX9jzzQbtFnh3qO0hQOQsalG1yG51HyNyHLb40RGTClpCUfxs00yA1VvsNJG+ZsYVCs99+nQPEFQ5PkkM1QRLt0wfVFhizlPmL53zjuD9Ko64LG2PQACyno6P/r1h/nocWu2gBiGgNRYDG7N4ycKbmGPqJ/iHOSvep1FoDd1nS1jZIxNWutXION7pNmOUfeJ9ahkxEK2C1+ZA==
  template:
    metadata:
      name: plex-claim
      namespace: media
