---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-claim
  namespace: media
spec:
  encryptedData:
    PLEX_CLAIM: AgAvVNWG1fw+CFcp2vu3o2F4T+YuBV+lwYRze3NnwADpTbCCYlNka7XFS911RV4HDYGWgFHTrbnfw2ubV6sjwkNiVBNQIExe2o513pkcxxzVz7yrBcHML6rZneathqmOOf24t5oA1RRaIvO1EPh2r1kSaz8NA+pFlSXh5fyWraCZx/HBCRLwUwfijmHRNTpagdJ0ulBcoTn80p9Ky7YYP2DNhdHrztj7JdQ1396AFeFRAyqtvLa6iNS1Xz3dQBGayYxX1ZsS4JREF7cRVjpKBKPeaPVvMXyxR3jpT+ZiLLjJ2Z5IgdSZKE07U2nrc0ll9kRTgaoSLn111h9WJDDkbtGS6dYaxhCGnHyA8YXZzzZmc4guD47L7dudIvDw1wh/0a83pFWG/+BJm7DL17if9INW49COF92nDGzIHVTMllrd/GJs6O/HQ8j6IyDwGrbSHpYTGaIooV77Hpgfij3ewQ8yL27MLh0QM6LFC5/9QXy1UE3p0TmynguU/PHSUELa2R9BWtR9apvzpnjjlBtFT3S74Ju4uATMqIUgo7JnkLg210c2s722bN9+z9aiEBCv70BgzsnFLC38U9lpXutNcbGSv0BlUqYnuZPu8ayoU7LD4Ls8TlX01b+0ecSFxB+sYubBbQhcaUpieNwe3OuvMcpaVpcrgyAVgJuKRemyXedSXgaPKOdPKNxNY2HmELzf8eSUmAtNpMhXtcNW38xYHCrD/rk5McZlwTz5tQ==
  template:
    metadata:
      name: plex-claim
      namespace: media
