# One-time Job: creates the revolt-uploads bucket in your existing MinIO
# Runs against minio.minio.svc.cluster.local
apiVersion: batch/v1
kind: Job
metadata:
  name: stoat-createbuckets
  namespace: stoat
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: createbuckets
          image: docker.io/minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              while ! /usr/bin/mc ready stoat-minio; do
                /usr/bin/mc alias set stoat-minio http://minio.minio.svc.cluster.local:9000 stoat "${MINIO_STOAT_PASSWORD}";
                echo 'Waiting for MinIO...' && sleep 2;
              done
              /usr/bin/mc mb --ignore-existing stoat-minio/revolt-uploads
              /usr/bin/mc anonymous set download stoat-minio/revolt-uploads
              exit 0
          env:
            - name: MINIO_STOAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stoat-minio-credentials
                  key: password