# Seal rabbit-credentials:
#   kubectl create secret generic rabbit-credentials -n stoat \
#     --from-literal=RABBITMQ_DEFAULT_USER=<USER> \
#     --from-literal=RABBITMQ_DEFAULT_PASS=<PASS> \
#     --dry-run=client -o yaml \
#     | kubeseal --controller-name sealed-secrets-controller \
#                --controller-namespace kube-system \
#                --format yaml
# Replace the encryptedData values below with the output
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbit-credentials
  namespace: stoat
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    RABBITMQ_DEFAULT_USER: SEAL_ME
    RABBITMQ_DEFAULT_PASS: SEAL_ME
  template:
    metadata:
      name: rabbit-credentials
      namespace: stoat
---
# Seal env-web:
#   kubectl create secret generic env-web -n stoat \
#     --from-literal=REVOLT_PUBLIC_URL=https://stoat.example.com \
#     --from-literal=VITE_API_URL=https://stoat.example.com/api \
#     --from-literal=VITE_WS_URL=wss://stoat.example.com/ws \
#     --from-literal=VITE_MEDIA_URL=https://stoat.example.com/autumn \
#     --from-literal=VITE_PROXY_URL=https://stoat.example.com/january \
#     --dry-run=client -o yaml \
#     | kubeseal --controller-name sealed-secrets-controller \
#                --controller-namespace kube-system \
#                --format yaml
# Replace the encryptedData values below with the output
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: env-web
  namespace: stoat
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    REVOLT_PUBLIC_URL: SEAL_ME
    VITE_API_URL: SEAL_ME
    VITE_WS_URL: SEAL_ME
    VITE_MEDIA_URL: SEAL_ME
    VITE_PROXY_URL: SEAL_ME
  template:
    metadata:
      name: env-web
      namespace: stoat
---
# Seal stoat-minio-credentials:
#   kubectl create secret generic stoat-minio-credentials -n stoat \
#     --from-literal=password=<MINIO_STOAT_PASSWORD> \
#     --dry-run=client -o yaml \
#     | kubeseal --controller-name sealed-secrets-controller \
#                --controller-namespace kube-system \
#                --format yaml
# Replace the encryptedData value below with the output
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stoat-minio-credentials
  namespace: stoat
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: SEAL_ME
  template:
    metadata:
      name: stoat-minio-credentials
      namespace: stoat
