apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transit-token
  namespace: vault
spec:
  encryptedData:
    TRANSIT_TOKEN: AgCwaKVbNcvjiApgTPD9BrutJTb4l+7tXZxORWgZU9GKusaacNJJKMgReOwetR/7VSIdElVt1iTOaXv/6FCtFdewfTLhGAERLjIAAedX5tVeQHCSfDUfLugfklDn57AZ3z4P+t67xaoHauifMq6CC9SDnnRGPRlfNwEtlPeE4b7pFMye9iBVBtZxr2XlOXPBWaKqTcX/6zNYSZMZaYL7gjPMiwBKLbOAcCshLc3qCWCxYlIvPnob2tGOYBIBpE7Ke0Dv5Bd9RpkyPD82t4bnV/i0+jYwcb2hLkqD7rY5576CagAF+HMWIMGpQg6MHUeE57A2xOI97qlfFTuH5UqREwJ6fVS0F4ShU0SbKu3GAWIva5DDFXFLeawMPNEstxegmsN1CZetg+bxNBg5qeYQvoZ5Dd1ViU1YK31N3kKtjv2x/SkIfpstXHWADENPJL39Cyqim19T0dG0VMuHgc6Hz06RhiEGe9Onb9C+WMNy2uXND0wDKHJ05aEh+weBx6qvZpokRFUDGa1Q/eWIU6AmczdTE1/hxf1aD+wfqM2qUvLxrIaSQESltZ+XFxJfqohcTeDw9ISXFtaAMOab2vKDk92ZqQxT18BNdVRY0zu66MCCfy5+hcmP/UZ2uiG7UxPfUtlreizD1bUX1BX6GO2ACmb+cE/Gdwf4H6lI2mwKAnPqFdHpeJ6Wdy5GOIk5ZS6jpAykUnpTzkhMvhiwLk4/DqiNwwx56eqVCxJLODyHWJ5W6MQ7xlfQc6pQ4A/iW2Ofek5nya3UGTgM6zYHUMk8jw4g24y6HBsTfHvZYTAhGD1mw6wNhh7qAnPHz8ldMWOWZg==
  template:
    metadata:
      name: transit-token
      namespace: vault
