apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transit-token
  namespace: vault
spec:
  encryptedData:
    TRANSIT_TOKEN: AgBRZrjuabI4h1wp4W0uuyldsQAGkxTS7uqQTGgZlRSDvAyXBgAi20wXIpjgX+Mpm/JvGf/ajBQvtxqGScw04goHHMH3gTRP/M12U6A+dk5rThMUDI7eOLguUz82MvtcHoToVEZ2S/HtQP5aM5SXxggZvAcWCHrGFGDBBXcdPtlIDSZIllqB+YgY8Chs1R/vTMIkltxGaXPL18DLXeOC1gPXLk7UKP51Kvr/NlXqDMVgw6XA/pzok3AI5KmcmU4J2iDSCSJjND4/Ghng0aKBpBcMM2BnTkXqAo8oghnimFMtQmF/d2GGu9P0zewzMljDmVhzLDcTPUzXJH0ceblihOUUjngGHuA9LY9sfCg818gVk1+q2yVV7uBEindLi1t1H2wpBYaTh/e2XmPzeapC34Ow9/ngyxYPudnZ3trb1hjVY+rxxvUV1kk51oUvH0iXncCWqruufIRdpWBIUB1TSkypCIoycPVn2eQQuMs5epgoZ4fPzvv1XVpLdw+luRIM5IOTAOQbCCdIyJrFqokxUcsTsMCToFheBpdJuDZoOW/bDqt7B8Z5HGgaxnqG8WfixccsUDu9c7GOLReUJiL4iVyvZ1tdSVDQ6XqqoFtXxaACYy7k36oCdSA/xUDtUURKyrJtCy/7sPcOH037gwlBq2iODKaHnFifxgeu0GWQvJJtcX14lPgURh8Ca8p7ON2v4/h8Iv2Tz/VXkARfzbCSXxzSWlyotjRQsJt2tlxthGthYY6hd4mTAV1L4WyOKpuTRWu29IrGfhtvY4U+iVA7gzL4juLsFNomZ8sPz3GmKUxu392oqcm0bOONLnknX7Br3g==
  template:
    metadata:
      name: transit-token
      namespace: vault
