---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transit-token
  namespace: vault
spec:
  encryptedData:
    TRANSIT_TOKEN: AgAXixVJ9SKhHR+UPS3EbxCEE+9LDzJAeH1Unz6U9IV6lqg9+uQkigmL6pebGvrd2luN9AGK9X6kzWpX4rxLk6JY8zjWP9TK/jCTlUq5eCHB3JyDXypoUMUfRYC8l0WPhiTsZDjhWtu4jZpvBpQRfSJ0yjKHvxAAywV6CILCJypf+LopqDQymCYmaGVRifP6AmhG7LhDARE6EUvJKGqcLtyrnFgvCMTpx77Ig7Tdtdp3razQOkvMgjtmA7WWbWjotIBe+zZks1RlsY2wyv452D4GBHXMcVMpg64wJZrENGTPAi3jefl6aXXY/pYtTd6nHUvz76D+NtGTUiWr8aZEI0izZx2/5E5gcADImrxCk/q5cqq5zT+6nZOZzcrNBN3ZP7glG52zqk5OsBNptyjA+tOIm6GOu3TFFjo6P8GbE6aVC0CaVbDfVwf5EEGyVGrJvI9OrS63ZTZJet0uNM2JPEkRGjlRZ857Lnxjm5UECdjiYAbNziQsMRS72rt8+206WxQoICeRmBvkW4JGKDhS3VmlJ7JpmYrWTW49k8wFPtj2n8lfn/l6Q6CDtei/5mX6VXCUtUOlrAb1NX4ix0dC2bb5SzsciGAL4c0AQvXUAhcUO8zDkLw8X7IutoiAtYCYXmU+RdRzYRI5YP1qwz0I7o9pxBJEI2M4O/rm+R/3ARpyJl9qAzru397AtQ9kwJQUQDAdJo7Nd7RoW095AyPZKq88utiVntcPcMA9wIsaUcF7khVqTxvtykyvZqS8iPGswuCHOpnb9l54Mxkv3r9Kwty38thdInj6QZ83wZxu89mfz0H6YmInQZaW48OZMoyH/w==
  template:
    metadata:
      name: transit-token
      namespace: vault
