apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: homelab
      namespace: traefik
      sectionName: websecure
  hostnames:
    - argocd.homelab.local
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80